model_versions: "v1.0.0"
choosen_method: "Random Forest"
methods:
  - name: "Decision Tree"
    config:
      criterion : "entropy"
      max_depth: 10
      random_state : 42
  - name: "Random Forest"
    config:
      criterion : "entropy"
      n_estimators: 200
      random_state : 42
  - name: "Gradient Boosting"
    config:
      n_estimators: 200
      random_state : 42
